### ISSUE TITLE
Naver Login Android SDK 를 4.2.0 이상으로 올릴 시 크래쉬

### ISSUE THREAD

**Issue by bhbac-nhnent** [naver/cafe-sdk-unity#14]
안녕하세요.

Naver Unity PLUG SDK 에는 Naver Login Android SDK 4.1.4 jar 빌드가 포함되어 있는데요,
이를 제거하고 Naver Login Android SDK 4.2.0 이상으로 올릴 경우
PLUG 로그인 중에 크래쉬가 발생합니다.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com..., PID: 20035
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nhn/android/naverlogin/connection/NetworkState$RetryListener;
        at com.naver.plug.cafe.login.LoginHelper$LoginType$1.builder(LoginHelper.java:99)
        at com.naver.plug.cafe.login.LoginHelper$LoginType$1.login(LoginHelper.java:104)
        at com.naver.glink.android.sdk.c$2.a(G.java:180)
        at com.naver.plug.core.b.a(CoreDelegate.java:26)
        at com.naver.plug.core.api.request.Request.handleAuthenticationError(Request.java:176)
        at com.naver.plug.core.api.request.Request.executeRetry(Request.java:161)
        at com.naver.plug.core.api.request.Request.lambda$execute$2(Request.java:109)
        at com.naver.plug.core.api.request.Request$$Lambda$3.onErrorResponse(Unknown Source:8)
        at com.android.volley.Request.deliverError(Request.java:564)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

이것은 Naver Login Android SDK 4.1.4 이하에 존재하던 NetworkState 클래스가 4.2.0 부터 제거되었기 때문인데요,
![image](https://user-images.githubusercontent.com/17632448/182759838-6614a696-28d0-477d-8281-bd7be07cb60e.png)
![image](https://user-images.githubusercontent.com/17632448/182759920-c77829f7-d2c7-49d6-a57f-109f95c81579.png)

이 클래스는 4.1.4 이하에서도, 사용하지 않더라도 Naver 로그인에는 문제가 없습니다.

현재 Naver Login Android SDK는 4.대 버전은 4.4.1까지,
https://mvnrepository.com/artifact/com.naver.nid/naveridlogin-android-sdk
5.대 버전은 group id, artifact id 가 변경되어 5.1.1 까지 배포된 상태이고,
https://mvnrepository.com/artifact/com.navercorp.nid/oauth
구 버전은 각종 이슈가 존재하여(아래 이슈만 하더라도 4.2.3에서 수정되었습니다.) 가급적 최신 버전의 적용이 필요합니다.
https://developers.naver.com/forum/posts/25715

그러므로 cafe sdk 에서 naver id 로그인시 NetworkState 클래스 참조를 제거하여 최소한 Naver Login Android SDK 4.1.4 가 아닌, 그 이상의 버전으로 업데이트 할 수 있도록 수정을 부탁드립니다.

**Comment by bhbac-nhnent** [comment]
2022년부터 '공식게임카페'가 종료되고 '라운지'로 기능이 넘어가면서
https://section.cafe.naver.com/ca-fe/home/notices/1696
PLUG SDK는 deprecated 되고'네이버 게임 SDK'로 이전해야 하는 것으로 보이므로
https://navergame.gitbook.io/naver-game/
이슈는 종료하도록 하겠습니다.
